<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>Ter22.Windows.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/Ter22.Windows/Ter22.Windows.csproj" /></ItemGroup>
</Project>
